name: Pull-Request-Created
on: 
  workflow_dispatch:
 
env:
  APP_NAME: myfirstspa
  ACR_HELM_REPO_NAME: helm/apptemplate
  ACR_HELM_CHART_NAME: apptemplate
  AKS_NAME: aksclusterdemo
  HOST_URL: pr-review.liventuspoc.com
jobs:
  build:
    name: Spin_Preview_Environment
    #if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
     # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: 'generate version tags'
      id: vars
      run: |

         url_tag_suffix=${{ github.event.number }}
         if [ -z "${url_tag_suffix}" ]; then
         echo "this is a test inside"
         url_tag_suffix=$(git rev-parse --short=7 ${{ github.sha }})
         fi
         echo ::set-output name=url_tag::pr-${{ env.APP_NAME }}-${url_tag_suffix}
         echo ::set-output name=pr_url::${url_tag}.${{env.HOST_URL}}
         echo  URL TAG Suffix -${url_tag_suffix}
         echo  URL TAG -${url_tag}
         echo  PR URL-${pr_url}
    